/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Font;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class bill extends javax.swing.JFrame {

    /**
     * Creates new form bill
     */
    
    public bill() {
        initComponents();
    }
    
 public bill( String cnam,String fnam,String ad,String mobn, int chn,String cmp,String fue,String mod,int engn,int vcost,int dep,int rem,int tot) {
        initComponents();
      bil.setText("-------------------------------------------------------------------------------------------------------------");
      bil.setText(bil.getText()+"\nKHURANA MOTORS\t\t         HONDA SHOWROOM\n243, A.B. Road DEWAS 455001(M.P.)\t         Ph : 222176,407072\nE-mail : khuranmotors@gmail.com\t         Date :- \n-------------------------------------------------------------------------------------------------------------");
      bil.setText(bil.getText()+"\nCUSTOMER DETAILS :-\t\tRecipt No. :");
      bil.setText(bil.getText()+"\nCustomer Name : "+cnam);
      bil.setText(bil.getText()+"\nFather Name : "+fnam);
      bil.setText(bil.getText()+"\nAddress : "+ad);
      bil.setText(bil.getText()+"\nMob No : "+mobn);
      bil.setText(bil.getText()+"\n------------------------------------------------------------------------------------------------------------");
      bil.setText(bil.getText()+"\nVEHICLE DETAILS :-");
      bil.setText(bil.getText()+"\nChassis No. : "+chn);
      bil.setText(bil.getText()+"\n\nCompany : "+cmp);
      bil.setText(bil.getText()+"\n\nFuel Type : "+fue);
      bil.setText(bil.getText()+"\n\nModel No. : "+mod);
      bil.setText(bil.getText()+"\n\nEngine No. : "+engn);
      bil.setText(bil.getText()+"\n------------------------------------------------------------------------------------------------------------");
      bil.setText(bil.getText()+"\nOTHER DETAILS :-");
      bil.setText(bil.getText()+"\nM.R No.: ");
      bil.setText(bil.getText()+"\nM.R Date : ");
      bil.setText(bil.getText()+"\nTin No.: ");
      bil.setText(bil.getText()+"\n------------------------------------------------------------------------------------------------------------");
      bil.setText(bil.getText()+"\nPAYMENT DETAILS :-");
      bil.setText(bil.getText()+"\nVehicle Cost Rs.: "+vcost);
      bil.setText(bil.getText()+"\nDeposite Amount : "+dep);
      bil.setText(bil.getText()+"\nRemaining Amount : "+rem);
      bil.setText(bil.getText()+"\nTOTAL Rs.: "+tot);
      bil.setText(bil.getText()+"\n\t\t\t              For Khurana Motors ");
      bil.setText(bil.getText()+"\n\n\nCustomer's Signature\t\t             Authorised Signature");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bil = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        bil.setColumns(20);
        bil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bil.setRows(5);
        jScrollPane1.setViewportView(bil);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 550, 640);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 650, 110, 20);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 650, 110, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
      
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (bil.getText().isEmpty())
   {
       JOptionPane.showMessageDialog(null, "Please add data");
   }
else
   {
  try { 
            bil.print();
        }   catch (PrinterException ex) { 
                Logger.getLogger(bill.class.getName()).log(Level.SEVERE, null, ex);
            } 
   }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Navbar().setExtendedState(Navbar.NORMAL);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
